# Generated by Django 3.2.5 on 2021-07-30 16:11

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to=books.models.upload_image_books),
        ),
    ]
